server:
  port: 9999

spring:
  application:
    name: caliber-zuul
  cloud: 
    config: 
      uri: http://localhost:8888

security:
  basic:
    enabled: false
    
info:
  component: Caliber Gateway
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
#zuul:
#routes:
#    batches:
#     path: /batches/**
#    serviceId: batch-service
#   strip-prefix: false
#trainees:
# path: /trainees/**
#serviceId: user-service
#strip-prefix: false
#trainers:
#  path: /trainers/**
#   serviceId: user-service
#    strip-prefix: false

      